/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    SafeCode: typeof import('./../components/safe-code.vue')['default']
    StoreGoodsItem: typeof import('./../components/store-goods-item.vue')['default']
  }
}
