/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index" |
       "/pages/auth/login" |
       "/pages/common/error" |
       "/pages/common/upgrade" |
       "/pages/common/webview-custom" |
       "/pages/common/webview" |
       "/pages/main/all-bb" |
       "/pages/main/dengji-1" |
       "/pages/main/dengji-2" |
       "/pages/main/dengji-3" |
       "/pages/main/dengji-4" |
       "/pages/main/wenjuantianbao" |
       "/pages/main/zipingbiao" |
       "/pages/tabs/home" |
       "/pages/tabs/logs" |
       "/pages/tabs/mine";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/tabs/home" | "/pages/tabs/logs" | "/pages/tabs/mine"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
